// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetClinic.Infrastructure.Data;

#nullable disable

namespace PetClinic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510193525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PetClinic.Core.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "110 W. Liberty St.",
                            City = "Madison",
                            FirstName = "George",
                            LastName = "Franklin",
                            Telephone = "6085551023"
                        },
                        new
                        {
                            Id = 2,
                            Address = "638 Cardinal Ave.",
                            City = "Sun Prairie",
                            FirstName = "Betty",
                            LastName = "Davis",
                            Telephone = "6085551749"
                        },
                        new
                        {
                            Id = 3,
                            Address = "2693 Commerce St.",
                            City = "McFarland",
                            FirstName = "Eduardo",
                            LastName = "Rodriquez",
                            Telephone = "6085558763"
                        },
                        new
                        {
                            Id = 4,
                            Address = "563 Friendly St.",
                            City = "Windsor",
                            FirstName = "Harold",
                            LastName = "Davis",
                            Telephone = "6085553198"
                        },
                        new
                        {
                            Id = 5,
                            Address = "2387 S. Fair Way",
                            City = "Madison",
                            FirstName = "Peter",
                            LastName = "McTavish",
                            Telephone = "6085552765"
                        },
                        new
                        {
                            Id = 6,
                            Address = "105 N. Lake St.",
                            City = "Monona",
                            FirstName = "Jean",
                            LastName = "Coleman",
                            Telephone = "6085552654"
                        },
                        new
                        {
                            Id = 7,
                            Address = "1450 Oak Blvd.",
                            City = "Monona",
                            FirstName = "Jeff",
                            LastName = "Black",
                            Telephone = "6085555387"
                        },
                        new
                        {
                            Id = 8,
                            Address = "345 Maple St.",
                            City = "Madison",
                            FirstName = "Maria",
                            LastName = "Escobito",
                            Telephone = "6085557683"
                        },
                        new
                        {
                            Id = 9,
                            Address = "2749 Blackhawk Trail",
                            City = "Windsor",
                            FirstName = "David",
                            LastName = "Schroeder",
                            Telephone = "6085559435"
                        },
                        new
                        {
                            Id = 10,
                            Address = "2335 Independence La.",
                            City = "Waunakee",
                            FirstName = "Carlos",
                            LastName = "Estaban",
                            Telephone = "6085555487"
                        });
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2010, 9, 7),
                            Name = "Leo",
                            OwnerId = 1,
                            PetTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2012, 8, 6),
                            Name = "Basil",
                            OwnerId = 2,
                            PetTypeId = 6
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2011, 4, 17),
                            Name = "Rosy",
                            OwnerId = 3,
                            PetTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(2010, 3, 7),
                            Name = "Jewel",
                            OwnerId = 3,
                            PetTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(2010, 11, 30),
                            Name = "Iggy",
                            OwnerId = 4,
                            PetTypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(2010, 1, 20),
                            Name = "George",
                            OwnerId = 5,
                            PetTypeId = 4
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(2012, 9, 4),
                            Name = "Samantha",
                            OwnerId = 6,
                            PetTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(2012, 9, 4),
                            Name = "Max",
                            OwnerId = 6,
                            PetTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(2011, 8, 6),
                            Name = "Lucky",
                            OwnerId = 7,
                            PetTypeId = 5
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(2007, 2, 24),
                            Name = "Mulligan",
                            OwnerId = 8,
                            PetTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(2010, 3, 9),
                            Name = "Freddy",
                            OwnerId = 9,
                            PetTypeId = 5
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(2010, 6, 24),
                            Name = "Lucky",
                            OwnerId = 10,
                            PetTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(2012, 6, 8),
                            Name = "Sly",
                            OwnerId = 10,
                            PetTypeId = 1
                        });
                });

            modelBuilder.Entity("PetClinic.Core.Entities.PetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "cat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "dog"
                        },
                        new
                        {
                            Id = 3,
                            Name = "lizard"
                        },
                        new
                        {
                            Id = 4,
                            Name = "snake"
                        },
                        new
                        {
                            Id = 5,
                            Name = "bird"
                        },
                        new
                        {
                            Id = 6,
                            Name = "hamster"
                        });
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "radiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "surgery"
                        },
                        new
                        {
                            Id = 3,
                            Name = "dentistry"
                        });
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "James",
                            LastName = "Carter"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Helen",
                            LastName = "Leary"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Linda",
                            LastName = "Douglas"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Rafael",
                            LastName = "Ortega"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Henry",
                            LastName = "Stevens"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Sharon",
                            LastName = "Jenkins"
                        });
                });

            modelBuilder.Entity("PetClinic.Core.Entities.VetSpecialty", b =>
                {
                    b.Property<int>("VetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VetId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("VetSpecialties");

                    b.HasData(
                        new
                        {
                            VetId = 2,
                            SpecialtyId = 1
                        },
                        new
                        {
                            VetId = 3,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 3,
                            SpecialtyId = 3
                        },
                        new
                        {
                            VetId = 4,
                            SpecialtyId = 2
                        },
                        new
                        {
                            VetId = 5,
                            SpecialtyId = 1
                        });
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "rabies shot",
                            PetId = 7,
                            VisitDate = new DateOnly(2013, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            Description = "rabies shot",
                            PetId = 8,
                            VisitDate = new DateOnly(2013, 1, 2)
                        },
                        new
                        {
                            Id = 3,
                            Description = "neutered",
                            PetId = 8,
                            VisitDate = new DateOnly(2013, 1, 3)
                        },
                        new
                        {
                            Id = 4,
                            Description = "spayed",
                            PetId = 7,
                            VisitDate = new DateOnly(2013, 1, 4)
                        });
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Pet", b =>
                {
                    b.HasOne("PetClinic.Core.Entities.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetClinic.Core.Entities.PetType", "PetType")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("PetType");
                });

            modelBuilder.Entity("PetClinic.Core.Entities.VetSpecialty", b =>
                {
                    b.HasOne("PetClinic.Core.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetClinic.Core.Entities.Vet", "Vet")
                        .WithMany("VetSpecialties")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Visit", b =>
                {
                    b.HasOne("PetClinic.Core.Entities.Pet", "Pet")
                        .WithMany("Visits")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Pet", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PetClinic.Core.Entities.Vet", b =>
                {
                    b.Navigation("VetSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
